// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ServerDeleteServerReader is a Reader for the ServerDeleteServer structure.
type ServerDeleteServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServerDeleteServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServerDeleteServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewServerDeleteServerOK creates a ServerDeleteServerOK with default headers values
func NewServerDeleteServerOK() *ServerDeleteServerOK {
	return &ServerDeleteServerOK{}
}

/*
ServerDeleteServerOK describes a response with status code 200, with default header values.

OK response.
*/
type ServerDeleteServerOK struct {
}

// IsSuccess returns true when this server delete server o k response has a 2xx status code
func (o *ServerDeleteServerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this server delete server o k response has a 3xx status code
func (o *ServerDeleteServerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this server delete server o k response has a 4xx status code
func (o *ServerDeleteServerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this server delete server o k response has a 5xx status code
func (o *ServerDeleteServerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this server delete server o k response a status code equal to that given
func (o *ServerDeleteServerOK) IsCode(code int) bool {
	return code == 200
}

func (o *ServerDeleteServerOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/server/{serverID}][%d] serverDeleteServerOK ", 200)
}

func (o *ServerDeleteServerOK) String() string {
	return fmt.Sprintf("[DELETE /v1/server/{serverID}][%d] serverDeleteServerOK ", 200)
}

func (o *ServerDeleteServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
