// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Masato516/vuls-client-go-swagger/models"
)

// ServerGetServerDetailByUUIDReader is a Reader for the ServerGetServerDetailByUUID structure.
type ServerGetServerDetailByUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServerGetServerDetailByUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServerGetServerDetailByUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewServerGetServerDetailByUUIDOK creates a ServerGetServerDetailByUUIDOK with default headers values
func NewServerGetServerDetailByUUIDOK() *ServerGetServerDetailByUUIDOK {
	return &ServerGetServerDetailByUUIDOK{}
}

/*
ServerGetServerDetailByUUIDOK describes a response with status code 200, with default header values.

OK response.
*/
type ServerGetServerDetailByUUIDOK struct {
	Payload *models.ServerGetServerDetailByUUIDResponseBody
}

// IsSuccess returns true when this server get server detail by Uuid o k response has a 2xx status code
func (o *ServerGetServerDetailByUUIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this server get server detail by Uuid o k response has a 3xx status code
func (o *ServerGetServerDetailByUUIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this server get server detail by Uuid o k response has a 4xx status code
func (o *ServerGetServerDetailByUUIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this server get server detail by Uuid o k response has a 5xx status code
func (o *ServerGetServerDetailByUUIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this server get server detail by Uuid o k response a status code equal to that given
func (o *ServerGetServerDetailByUUIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *ServerGetServerDetailByUUIDOK) Error() string {
	return fmt.Sprintf("[GET /v1/server/uuid/{serverUuid}][%d] serverGetServerDetailByUuidOK  %+v", 200, o.Payload)
}

func (o *ServerGetServerDetailByUUIDOK) String() string {
	return fmt.Sprintf("[GET /v1/server/uuid/{serverUuid}][%d] serverGetServerDetailByUuidOK  %+v", 200, o.Payload)
}

func (o *ServerGetServerDetailByUUIDOK) GetPayload() *models.ServerGetServerDetailByUUIDResponseBody {
	return o.Payload
}

func (o *ServerGetServerDetailByUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerGetServerDetailByUUIDResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
