// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RoleDeleteRoleReader is a Reader for the RoleDeleteRole structure.
type RoleDeleteRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoleDeleteRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRoleDeleteRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRoleDeleteRoleOK creates a RoleDeleteRoleOK with default headers values
func NewRoleDeleteRoleOK() *RoleDeleteRoleOK {
	return &RoleDeleteRoleOK{}
}

/*
RoleDeleteRoleOK describes a response with status code 200, with default header values.

OK response.
*/
type RoleDeleteRoleOK struct {
}

// IsSuccess returns true when this role delete role o k response has a 2xx status code
func (o *RoleDeleteRoleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this role delete role o k response has a 3xx status code
func (o *RoleDeleteRoleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this role delete role o k response has a 4xx status code
func (o *RoleDeleteRoleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this role delete role o k response has a 5xx status code
func (o *RoleDeleteRoleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this role delete role o k response a status code equal to that given
func (o *RoleDeleteRoleOK) IsCode(code int) bool {
	return code == 200
}

func (o *RoleDeleteRoleOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/role/{roleID}][%d] roleDeleteRoleOK ", 200)
}

func (o *RoleDeleteRoleOK) String() string {
	return fmt.Sprintf("[DELETE /v1/role/{roleID}][%d] roleDeleteRoleOK ", 200)
}

func (o *RoleDeleteRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
