// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Masato516/vuls-client-go-swagger/models"
)

// RoleUpdateRoleReader is a Reader for the RoleUpdateRole structure.
type RoleUpdateRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoleUpdateRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRoleUpdateRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRoleUpdateRoleOK creates a RoleUpdateRoleOK with default headers values
func NewRoleUpdateRoleOK() *RoleUpdateRoleOK {
	return &RoleUpdateRoleOK{}
}

/*
RoleUpdateRoleOK describes a response with status code 200, with default header values.

OK response.
*/
type RoleUpdateRoleOK struct {
	Payload *models.RoleUpdateRoleResponseBody
}

// IsSuccess returns true when this role update role o k response has a 2xx status code
func (o *RoleUpdateRoleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this role update role o k response has a 3xx status code
func (o *RoleUpdateRoleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this role update role o k response has a 4xx status code
func (o *RoleUpdateRoleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this role update role o k response has a 5xx status code
func (o *RoleUpdateRoleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this role update role o k response a status code equal to that given
func (o *RoleUpdateRoleOK) IsCode(code int) bool {
	return code == 200
}

func (o *RoleUpdateRoleOK) Error() string {
	return fmt.Sprintf("[PUT /v1/role/{roleID}][%d] roleUpdateRoleOK  %+v", 200, o.Payload)
}

func (o *RoleUpdateRoleOK) String() string {
	return fmt.Sprintf("[PUT /v1/role/{roleID}][%d] roleUpdateRoleOK  %+v", 200, o.Payload)
}

func (o *RoleUpdateRoleOK) GetPayload() *models.RoleUpdateRoleResponseBody {
	return o.Payload
}

func (o *RoleUpdateRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleUpdateRoleResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
