// Code generated by go-swagger; DO NOT EDIT.

package lockfile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Masato516/vuls-client-go-swagger/models"
)

// LockfileUpdateLockfileReader is a Reader for the LockfileUpdateLockfile structure.
type LockfileUpdateLockfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LockfileUpdateLockfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLockfileUpdateLockfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLockfileUpdateLockfileOK creates a LockfileUpdateLockfileOK with default headers values
func NewLockfileUpdateLockfileOK() *LockfileUpdateLockfileOK {
	return &LockfileUpdateLockfileOK{}
}

/*
LockfileUpdateLockfileOK describes a response with status code 200, with default header values.

OK response.
*/
type LockfileUpdateLockfileOK struct {
	Payload *models.LockfileUpdateLockfileResponseBody
}

// IsSuccess returns true when this lockfile update lockfile o k response has a 2xx status code
func (o *LockfileUpdateLockfileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this lockfile update lockfile o k response has a 3xx status code
func (o *LockfileUpdateLockfileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lockfile update lockfile o k response has a 4xx status code
func (o *LockfileUpdateLockfileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this lockfile update lockfile o k response has a 5xx status code
func (o *LockfileUpdateLockfileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this lockfile update lockfile o k response a status code equal to that given
func (o *LockfileUpdateLockfileOK) IsCode(code int) bool {
	return code == 200
}

func (o *LockfileUpdateLockfileOK) Error() string {
	return fmt.Sprintf("[PUT /v1/lockfile/{lockfileID}][%d] lockfileUpdateLockfileOK  %+v", 200, o.Payload)
}

func (o *LockfileUpdateLockfileOK) String() string {
	return fmt.Sprintf("[PUT /v1/lockfile/{lockfileID}][%d] lockfileUpdateLockfileOK  %+v", 200, o.Payload)
}

func (o *LockfileUpdateLockfileOK) GetPayload() *models.LockfileUpdateLockfileResponseBody {
	return o.Payload
}

func (o *LockfileUpdateLockfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LockfileUpdateLockfileResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
