// Code generated by go-swagger; DO NOT EDIT.

package lockfile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// LockfileDeleteLockfileReader is a Reader for the LockfileDeleteLockfile structure.
type LockfileDeleteLockfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LockfileDeleteLockfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLockfileDeleteLockfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLockfileDeleteLockfileOK creates a LockfileDeleteLockfileOK with default headers values
func NewLockfileDeleteLockfileOK() *LockfileDeleteLockfileOK {
	return &LockfileDeleteLockfileOK{}
}

/*
LockfileDeleteLockfileOK describes a response with status code 200, with default header values.

OK response.
*/
type LockfileDeleteLockfileOK struct {
}

// IsSuccess returns true when this lockfile delete lockfile o k response has a 2xx status code
func (o *LockfileDeleteLockfileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this lockfile delete lockfile o k response has a 3xx status code
func (o *LockfileDeleteLockfileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lockfile delete lockfile o k response has a 4xx status code
func (o *LockfileDeleteLockfileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this lockfile delete lockfile o k response has a 5xx status code
func (o *LockfileDeleteLockfileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this lockfile delete lockfile o k response a status code equal to that given
func (o *LockfileDeleteLockfileOK) IsCode(code int) bool {
	return code == 200
}

func (o *LockfileDeleteLockfileOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/lockfile/{lockfileID}][%d] lockfileDeleteLockfileOK ", 200)
}

func (o *LockfileDeleteLockfileOK) String() string {
	return fmt.Sprintf("[DELETE /v1/lockfile/{lockfileID}][%d] lockfileDeleteLockfileOK ", 200)
}

func (o *LockfileDeleteLockfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
