// Code generated by go-swagger; DO NOT EDIT.

package pkg_cpe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PkgCpeDeleteCpeDeprecatedReader is a Reader for the PkgCpeDeleteCpeDeprecated structure.
type PkgCpeDeleteCpeDeprecatedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PkgCpeDeleteCpeDeprecatedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPkgCpeDeleteCpeDeprecatedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPkgCpeDeleteCpeDeprecatedOK creates a PkgCpeDeleteCpeDeprecatedOK with default headers values
func NewPkgCpeDeleteCpeDeprecatedOK() *PkgCpeDeleteCpeDeprecatedOK {
	return &PkgCpeDeleteCpeDeprecatedOK{}
}

/*
PkgCpeDeleteCpeDeprecatedOK describes a response with status code 200, with default header values.

OK response.
*/
type PkgCpeDeleteCpeDeprecatedOK struct {
}

// IsSuccess returns true when this pkg cpe delete cpe deprecated o k response has a 2xx status code
func (o *PkgCpeDeleteCpeDeprecatedOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pkg cpe delete cpe deprecated o k response has a 3xx status code
func (o *PkgCpeDeleteCpeDeprecatedOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pkg cpe delete cpe deprecated o k response has a 4xx status code
func (o *PkgCpeDeleteCpeDeprecatedOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pkg cpe delete cpe deprecated o k response has a 5xx status code
func (o *PkgCpeDeleteCpeDeprecatedOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pkg cpe delete cpe deprecated o k response a status code equal to that given
func (o *PkgCpeDeleteCpeDeprecatedOK) IsCode(code int) bool {
	return code == 200
}

func (o *PkgCpeDeleteCpeDeprecatedOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/pkgCpe/cpe][%d] pkgCpeDeleteCpeDeprecatedOK ", 200)
}

func (o *PkgCpeDeleteCpeDeprecatedOK) String() string {
	return fmt.Sprintf("[DELETE /v1/pkgCpe/cpe][%d] pkgCpeDeleteCpeDeprecatedOK ", 200)
}

func (o *PkgCpeDeleteCpeDeprecatedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
