// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Masato516/vuls-client-go-swagger/models"
)

// TaskGetTaskListReader is a Reader for the TaskGetTaskList structure.
type TaskGetTaskListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TaskGetTaskListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTaskGetTaskListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTaskGetTaskListOK creates a TaskGetTaskListOK with default headers values
func NewTaskGetTaskListOK() *TaskGetTaskListOK {
	return &TaskGetTaskListOK{}
}

/*
TaskGetTaskListOK describes a response with status code 200, with default header values.

OK response.
*/
type TaskGetTaskListOK struct {
	Payload *models.TaskGetTaskListResponseBody
}

// IsSuccess returns true when this task get task list o k response has a 2xx status code
func (o *TaskGetTaskListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this task get task list o k response has a 3xx status code
func (o *TaskGetTaskListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this task get task list o k response has a 4xx status code
func (o *TaskGetTaskListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this task get task list o k response has a 5xx status code
func (o *TaskGetTaskListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this task get task list o k response a status code equal to that given
func (o *TaskGetTaskListOK) IsCode(code int) bool {
	return code == 200
}

func (o *TaskGetTaskListOK) Error() string {
	return fmt.Sprintf("[GET /v1/tasks][%d] taskGetTaskListOK  %+v", 200, o.Payload)
}

func (o *TaskGetTaskListOK) String() string {
	return fmt.Sprintf("[GET /v1/tasks][%d] taskGetTaskListOK  %+v", 200, o.Payload)
}

func (o *TaskGetTaskListOK) GetPayload() *models.TaskGetTaskListResponseBody {
	return o.Payload
}

func (o *TaskGetTaskListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TaskGetTaskListResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
